name: GitHub Actions Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '16'

jobs:
  Backend-Tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Backend
        working-directory: backend
        run: mvn compile test-compile

      - name: Run Backend Tests
        working-directory: backend
        run: mvn test

      - name: Build Adoc PDF
        uses: tonynv/asciidoctor-action@v2
        with:
          program: "asciidoctor-pdf -a allow-uri-read -D . backend/src/main/asciidoc/index.adoc"

      - name: Upload Adoc PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs.pdf
          path: index.pdf

  Frontend-Tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Run Frontend Tests
        working-directory: client
        run: npm test